<div class="product-form">
    <input type="text" class="name" id="name" placeholder="Name">
    <hr>
    <input type="text" class="price" id="price" placeholder="Price">
    <hr>
    <input type="text" class="description" id="description" placeholder="Description">
    <hr>
    <input type="text" class="img" id="img" placeholder="Image">
    <hr>
    <button id="addProduct">Add Product</button>
</div>
<div class="table">
    <table>
        <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Image</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "widget": {
            }
        }
    }
</script>
