<!--<script>-->
<!--    require(["Bss_Routing/js/hello"], function (custom){-->
<!--        document.getElementById("hello").innerHTML = custom.getText();-->
<!--    });-->
<!--</script>-->
<div class="product_form">
        <input type="text" class="name" id="" placeholder="Name"> <hr>
        <input type="text" class="ip" id="" placeholder="Price"><hr>
        <input type="text" class="description" id="" placeholder="Description"><hr>
        <label for="">Avatar</label>
        <input type="file" class="img" id=""><hr>
        <button>ADD DEVICE</button>
</div>
<script type="text/x-magento-init">
    {
        ".product_form": {
            "exampleJs": {
            }
        }
    }
</script>


<h2 id="hello"></h2>
