<div class="form_add_intern">
    <form class="form create account form-create-account" action="/schema/index/inforcustomer" method="post"
          id="form-validate" data-mage-init='{"validation": {}}'>
        <fieldset class="fieldset create info">
            <legend class="legend"><span>Intern Information</span></legend>
            <br>
            <div class="field field-name required">
                <label><span>Name</span></label>
                <div class="control">
                    <input type="text" id="name" name="name" data-validate='{"required":true}'/>
                </div>
            </div>
            <div class="field required">
                <label><span>Date Of Birth</span></label>
                <div class="control">
                    <input type="date" id="birthday" name="birthday" data-validate='{"required":true}'/>
                </div>
            </div>
            <div class="field required">
                <label><span>Gender</span></label>
                <div class="control">
                    <select name="gender" id="gender">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                </div>
            </div>
            <div class="field required">
                <label><span>Address</span></label>
                <div class="control">
                    <input type="text" id="address" name="address" data-validate='{"required":true}'/>
                </div>
            </div>
            <div class="field required">
                <label><span>Email</span></label>
                <div class="control">
                    <input type="email" name="email" autocomplete="email" id="email" data-validate='{"required":true, "validate-email":true,equalTo:"#email"}'/>
                </div>
            </div>
            <div>
                <button type="submit" id="addIntern" value="1" name="submit">Submit</button>
            </div>
        </fieldset>
    </form>
</div>
